"""Router package — each module exposes a ``router`` APIRouter instance."""

from app.routers import (
    auth,
    apartments,
    rooms,
    catalog,
    leads,
    media,
    estimate,
    draft_rooms,
    ai,
    electrical,
    decoration,
    finishes,
    furniture_placements,
    room_state,
    render,
    photo_model,
    seller,
    admin_moderation,
    usta_profile,
    account,
)

__all__ = [
    "seller",
    "admin_moderation",
    "usta_profile",
    "account",
    "photo_model",
    "render",
    "auth",
    "apartments",
    "rooms",
    "catalog",
    "leads",
    "media",
    "estimate",
    "draft_rooms",
    "ai",
    "electrical",
    "decoration",
    "finishes",
    "furniture_placements",
    "room_state",
]
